export const categories = {
  data: [
    {
      id: "615097c4e60a790001b3a015",
      title: "پشتیبانی",
      englishTitle: "SUPPORT",
      description: "",
      mediaFiles: [],
      parentId: "",
      locations: [],
      childs: null,
      additionalData: "additionalData",
      isMainPageCategory: false,
      moduleType: 1,
      categoryCode: 1731,
      status: 2,
    },
    {
      id: "615097b3e60a790001b3a014",
      title: "مقالات",
      englishTitle: "ARTICLES",
      description: "",
      mediaFiles: [],
      parentId: "",
      locations: [],
      childs: null,
      additionalData: "additionalData",
      isMainPageCategory: false,
      moduleType: 1,
      categoryCode: 1730,
      status: 2,
    },
    {
      id: "6150978ae60a790001b3a013",
      title: "پروژه ها",
      englishTitle: "PORTFOLIOS",
      description: "",
      mediaFiles: [],
      parentId: "",
      locations: [],
      childs: null,
      additionalData: "additionalData",
      isMainPageCategory: false,
      moduleType: 1,
      categoryCode: 1729,
      status: 2,
    },
    {
      id: "61509760e60a790001b3a012",
      title: "آکادمی",
      englishTitle: "ACADEMY",
      description: "",
      mediaFiles: [],
      parentId: "",
      locations: [],
      childs: null,
      additionalData: "additionalData",
      isMainPageCategory: false,
      moduleType: 1,
      categoryCode: 1728,
      status: 2,
    },
    {
      id: "615092cee60a790001b3a009",
      title: "خدمات",
      englishTitle: "COMPANY_SERVICES",
      description: "خدمات",
      mediaFiles: [],
      parentId: "",
      locations: [],
      childs: null,
      additionalData: "",
      isMainPageCategory: false,
      moduleType: 1,
      categoryCode: 1719,
      status: 2,
    },
  ],
};
